### ISSUE TITLE
Tracking assignments and Projects

### ISSUE THREAD

**Issue by Regidan-codes** [Regidan-codes/ML-ZOOMCAMP2022#1]

**Comment by Regidan-codes** [comment]
ML-ZOOMCAMP 2022

## Todo

- [ ]  Introduction to Machine Learning
- [ ]  Machine Learning for Regression
- [ ]  Machine Learning for Classification
- [ ]  Evaluation Metrics for Classification
- [ ]  Deploying Machine Learning Models
- [ ]  Bento ML
- [ ]  Midterm Project
- [ ]  Neural Networks and Deep Learning
- [ ]  Serverless Deep Learning
- [ ]  Kubernetes and TensorFlow Serving
- [ ]  KServe 
- [ ]  Capstone Project
- [ ]  Article
- [ ]  Third project (optional)
