### ISSUE TITLE
Tracking Assignments and projects

### ISSUE THREAD

**Issue by Regidan-codes** [Regidan-codes/ML-ZOOMCAMP2022#2]
ML-ZOOMCAMP 2022

##Todo

ML-ZOOMCAMP 2022

## Todo

- [x]  Introduction to Machine Learning
- [ ]  Machine Learning for Regression
- [ ]  Machine Learning for Classification
- [ ]  Evaluation Metrics for Classification
- [ ]  Deploying Machine Learning Models
- [ ]  Bento ML
- [ ]  Midterm Project
- [ ]  Neural Networks and Deep Learning
- [ ]  Serverless Deep Learning
- [ ]  Kubernetes and TensorFlow Serving
- [ ]  KServe 
- [ ]  Capstone Project
- [ ]  Article
- [ ]  Third project (optional)

**Comment by golu098** [comment]
can you give me opportunity to do it?
